### ISSUE TITLE
No png output in linux installation

### ISSUE THREAD

**Issue by tapanis** [OOoLilyPond/OOoLilyPond#4]
I have been using OOoLilyPond for years.
Recently, I have started getting an error code and no output on my linux installation:

> Converting to PNG...
> warning: (gs -q -dNODISPLAY -dNOSAFER -dNOPAUSE -dBATCH -dEPSCrop -dAutoRotatePages=/None -dPrinted=false /tmp/lilypond-tmp-4238665)' failed `(256)

I don't have any such trouble in my Windows 10 installation.

If I change to eps output, I have no problems.

Ubuntu 21.10
LO 7.2.3.2.
OOoLP 1.1.2.

Tapani

**Comment by KlausBlum** [comment]
Hi Tapani,

Hmmm... that's strange. 
Did you switch to a newer LilyPond version or change something else in your setup?

AFAIK "gs" is GhostScript: LilyPond calls GhostScript after creating a ps file to convert it to other formats. 
256 seems to be an error number. 

A quick google search leads me to this: 
https://lists.gnu.org/archive/html/lilypond-user/2017-04/msg00116.html
Are you using a special font that cannot be found? 
Or could it be a directory /tmp that is not accessible?

HTH, 
Klaus

**Comment by bearhoney** [comment]
I am a first-time user and experience similar issues: in the config window, I have a choice of 5 output formats:
**png** --> Error: no png output is found.
**eps** --> Error: no eps output is found.
**pdf to svg** - Error: no pdf output is found.
With all three options above, the "Ly Output" window contains:
  _"/usr/bin/lilypond: unerkannte Option: »-b«"_
which means '_unknown option "-b"._' in German language.

**svg [-dcrop]** --> produces a large error popup:

```
 No svg output is found.

 If there are no compiler messages, you should check LilyPond's output messages by clicking the "Ly Output" button.

 Please make sure that

 1.) your settings for Staff Size etc. provide sufficient space for your musical snippet.

 (This is necessary if Ly Output reports successful compiling, but more than one file has been created
    --- or ---
 if Ly Output reports successful compiling, but no file has been created and error  messages talk about "...bad number of pages".)

 2.) your template and your code do not include "lilypond-book-preamble.ly".
 (This is necessary if Ly Output reports successful compiling, but only *.eps and/or *.pdf files have been created, but no *.svg files.)
```

while "Ly Output" shows (again in German, but mind the English error message just before the last line):

```
»/home/bearhoney/.cache/ooolilypond/tmp/OOoLilyPond.ly« wird verarbeitet
Analysieren...
Interpretation der Musik...
Vorverarbeitung der grafischen Elemente...
Zeilenumbrüche werden berechnet... 
Systeme erstellen... 
Warnung: ignoring unsupported formats (pdf)
Kompilation erfolgreich beendet
```
 
**svg** --> OK
This is the only output format that currently works for me.

My software:
Manjaro Linux (kernel 5.14)
LibreOffice v7.2.2.2
GNU LilyPond 2.23.6 (running Guile 2.2)
OOoLilyPond 1.1.2
pdf2svg 0.2.3-5

**Comment by KlausBlum** [comment]
Hi bearhoney, 
in your case the error message seems to have a different reason.

The "-b" option only is used for old LilyPond versions up to 2.10 and for some unknown reason, OLy thinks you have such an old version. (Maybe you had an old version installed before? Unfortunately, this is never checked again by OLy. I'll see how I can change this behavior. Congratulations - you've found a bug.)

To get OLy working again, you could try the following: 

- go to your home directory
- navigate to the subdirectory ".config"
- navigate to its subdirectory "ooolilypond"
- there you should find a text file named "config" (without extension)
- delete this "config" file an re-run OLy. 
 
Does it work now?

Viele Grüße, 
Klaus

**Comment by KlausBlum** [comment]
Oops, I was wrong: 
Indeed, OLy re-checks the LilyPond version every time the config dialog is closed via the OK button. 

But: 
When responding to a "lilypond --version" call, it seems that LilyPond 2.23 not only outputs its own version, but also the guile version. OLy assumes the latter as the LilyPond version... which is wrong. 

With Ly 2.22:
`C:\Program Files (x86)\LilyPond\usr\bin>lilypond --version`
`GNU LilyPond 2.22.1`

With Ly 2.23:
`C:\Program Files (x86)\LilyPond\usr\bin>lilypond --version`
`GNU LilyPond 2.23.5 (running Guile 1.8)`
In this case OLy assumes LilyPond v. 1.8 and uses the deprecated `-b` parameter that throws the error. 

I'll see what I can do.

**Comment by KlausBlum** [comment]
Here is a quick development release that hopefully fixes the issue with the unknown "-b" option:
https://github.com/OOoLilyPond/OOoLilyPond/releases/tag/v1.1.3
direct download:
https://github.com/OOoLilyPond/OOoLilyPond/releases/download/v1.1.3/OOoLilyPond-1.1.3.oxt

However I noticed another severe problem (at least on Windows - don't know if it's the same with Linux): 
With LilyPond 2.23, the automatic cropping does not work. It seems that lilypond-book-preamble has no effect. I have no idea why this happens. 
With LilyPond 2.22, everything is fine. 

Anyway, I hope this helps for the moment.

**Comment by KlausBlum** [comment]
Small update to the auto-crop problem mentioned in my last post: 

With LilyPond versions up to 2.23.4 everything works fine. However, with 2.23.5 it seems that the auto-crop feature is broken (at least on Windows). Instead of a small snippet you'll get a whole page with lots of empty space. 
**Therefore I'd recommend NOT to use LilyPond 2.23.5 for OOoLilyPond.**

**Comment by bearhoney** [comment]
Hi KlausBrum,

thank you, version 1.1.3 solved the '-b' issue for me - though it still shows up as v1.1.2 in Extension Manager. 
(tested on LibreOffice 7.2.2.2, GNU LilyPond 2.23.6 (running Guile 2.2), pdf2svg 0.2.3-5, Manjaro Linux (x86-64) )

**svg output works for me**, cropped and nice - even with the current LilyPond version!
The other output formats produce various issues on my system - either not cropped at all or not enough; or OLy does not find LilyPond's output, for various reasons. This also depends on the chosen template, which is difficult to master for a newbie like me.

More details from my [1.3.3 tests in a ODT document](https://c.gmx.net/@327719629986208024/wJn7VTOqRt-MDWuxpsPNWQ) (german language, accessible until 2022-01-08).

**Comment by KlausBlum** [comment]
Hi bearhoney, 

oops, indeed 1.1.3 shows up as 1.1.2 - I simply forgot to update the version number. That's corrected now. 

Thanks for your verbose testing and documentation. That helped me to understand what's going on.

As for the different templates, you got it right: 
[svg] and [svg -dcrop] are meant for the respective graphic file formats. 
(I'm surprised that you got no errors when using a svg format with a non-svg template. But that's the reason for the warning "ignoring unsupported formats (pdf)". When including "lilypond-book-preamble.ly", LilyPond wants to produce a pdf, which cannot be done by the svg backend. Still a mistery to many people, including myself.)

The best option should be to use the "pdf to svg" format with the "normal" templates, i.e. the non-svg-versions. 
(AFAIK LilyPond produces a ps file and calls external programs to convert it to png, eps or pdf.)

It seems the un-cropped images are a problem of the latest LilyPond version 2.23.5 (and maybe also 2.23.6 - I didn't even find it in the official downloads). 
Do you have the opportunity to try with Ly 2.23.4 (or earlier)? Or the latest "stable" version 2.22? 
Then cropping should work without problems. 

I've created a separate issue for the cropping problem: 
https://github.com/OOoLilyPond/OOoLilyPond/issues/5
If there are any news to that topic, I'll post them there. 

Hope this helps, 
Klaus

**Comment by tapanis** [comment]
> Hi Tapani,
> 
> Hmmm... that's strange. Did you switch to a newer LilyPond version or change something else in your setup?
> 
> AFAIK "gs" is GhostScript: LilyPond calls GhostScript after creating a ps file to convert it to other formats. 256 seems to be an error number.
> 
> A quick google search leads me to this: https://lists.gnu.org/archive/html/lilypond-user/2017-04/msg00116.html Are you using a special font that cannot be found? Or could it be a directory /tmp that is not accessible?
> 
> HTH, Klaus

Thanks for the reply. It is strange.

The tmp directory is accessible. I have the latest stable version of lilypond (2.22.1) installed. It works when I compile Lilypond files outside LibreOffice; the problem only occurs within Ooolilypond. I haven't made any changes to the configuration.

I tried with 2.23-5, but that threw up the same error.

Tapani

**Comment by KlausBlum** [comment]
Hi Tapani, 

another user has reported a similar issue: 
https://github.com/openlilylib/LO-ly/issues/33

Do you have a flatpak or snap installation (or anything else where every application is executed in its own sandbox)?

**Comment by KlausBlum** [comment]
No updates for two years now... closing.  
Please feel free to re-open if there are any news.
