### ISSUE TITLE
problem upgrading

### ISSUE THREAD

**Issue by kavol** [OOoLilyPond/OOoLilyPond#9]
Trying to open some files with notes, I have found that the notes are treated like PNG images, I cannot edit the source. Obviously, the extension does not work for me.

So I went to extension manager to check the extension, see there is an update to 1.1.8 (from 1.0.0 that I had installed originally), so I've tried to update ... and it failed with this error:

`Při instalaci rozšíření OOoLilyPond došlo k chybě. Chybová zpráva je: Nelze detekovat typ média: file:///tmp/8I2LyL_/sb5GRE_/d64958b6-fbfa-440f-8ca0-68ee539f9591 at /var/tmp/portage/app-office/libreoffice-7.4.4.2/work/libreoffice-7.4.4.2/desktop/source/deployment/registry/dp_registry.cxx:481
Rozšíření nebude instalováno.`

("Error installing OOoLilyPond extension. The error message is: Cannot detect media type: ... The extension will not be installed.")

I don't know when it worked for me for the last time, I haven't used it for about a year ... Currently, I have LibreOffice 7.4.4.2 installed, and I don't feel like downgrading to 6.x to see if it works with the old version ...

**Comment by KlausBlum** [comment]
Strange... this sounds like LibreOffice has a problem with installing (or running) extensions. 
AFAIK a _user profile reset_ can help to resolve this: 

1.) If possible, uninstall OOoLilyPond via the Extension Manager.

2.) Rename the LO profile folder as desribed here:
[https://wiki.documentfoundation.org/UserProfile#Resolving_corruption](https://wiki.documentfoundation.org/UserProfile#Resolving_corruption)
(under "Manual procedure (all versions)"!)

(A user who had the same problem has reported that deleting the subfolder "extensions" inside the user folder did the trick.
Other customizations in your LO installation might remain untouched by that. But it will affect every LO extension you have installed, so be prepared that you have to re-install them.)

3.) Reinstall OOoLilyPond


Does that help?

**Comment by KlausBlum** [comment]
Another thought: 
If the picture is not recognized as an OLy object, there are some _attributes_ missing that are attached to the picture after it has been inserted into the document. 
In case OLy has crashed after inserting the picture but before attaching the attributes, this could lead to such a non-recognized picture. 

Do you remember if you had such problems when creating the affected documents?

**Comment by kavol** [comment]
I don't have anything special in my profile, so I just deleted it. Trying to install the extension from the web (using download url on the commandline), it failed with the same error, while it worked after downloading the file and passing the local path. So probably this is the same problem as with trying to use the LO update mechanism and it is a bug in LO itself.

Now I can edit the notes by calling the extension explicitly - still it treats the object as an ordinary png image, trying to edit it opens graphical editor, but when I have it selected and chose to use the extension explicitly from the tools => extensions menu, it now opens the dialogue with source code and I can regenerate the image. I don't recall LO crashing when editing files with notes, but it is long time ago ... however, the problem that it treats the objects as images is with all the notes within all the documents I've tried (all of them created circa 12-18 months ago with version 1.0.0), and also if I create new object, trying to edit it, it treats it as image.

Probably, this can be closed then ... the upgrade issue now looks to me like a problem in LO, and I can live with the fact that the object linking doesn't work as expected, as long as I can edit the object via explicit extension call.

Thanks for your time.

**Comment by KlausBlum** [comment]
The update mechanism in LO has been broken quite some time ago. The only way to update an extension is to uninstall it, download the update and install the latter. That indeed seems to be an known problem in LO. 

Also, the only way to launch OLy is to call it explicitely. Apart from the menu, there also should be an "OLy" button in the toolbar. 
(On my machine, I've created a keyboard shortcut.) 
If you double-click an OLy object, it is treated as an ordinary image by LO. I'm sure, this also has been the case when you created your document. 

Cheers, 
Klaus
